sim_hrs: 42
template_dir: /glade/work/jaredlee/nsf_i-wrf/use_cases/renewable_energy/templates
wps_ins_dir: /glade/u/home/jaredlee/programs/WPS-4.6-dmpar-casper
wrf_ins_dir: /glade/u/home/jaredlee/programs/WRF-4.6
wps_run_dir: /glade/derecho/scratch/jaredlee/nsf_i-wrf/renewable_energy/wps
wrf_run_dir: /glade/derecho/scratch/jaredlee/nsf_i-wrf/renewable_energy/wrf
grib_dir: /glade/derecho/scratch/jaredlee/data/hrrr
ungrib_domain: full
icbc_model: HRRR
icbc_source: AWS
icbc_fc_dt: 0
icbc_analysis: False
hrrr_native: True
get_icbc: False
do_geogrid: False
do_ungrib: False
do_avg_tsfc: False
use_tavgsfc: False
do_metgrid: False
do_real: False
do_wrf: True
archive: False
account: NERP0002
