sim_hrs: 12
template_dir: /glade/work/jaredlee/workflow/templates
wps_ins_dir: /glade/u/home/jaredlee/programs/WPS-4.6-dmpar-casper
wrf_ins_dir: /glade/u/home/jaredlee/programs/WRF-4.6
wps_run_dir: /glade/derecho/scratch/jaredlee/workflow/wps
wrf_run_dir: /glade/derecho/scratch/jaredlee/workflow/wrf
grib_dir: /glade/derecho/scratch/jaredlee/data/gfs
ungrib_domain: full
icbc_model: GFS
icbc_source: GLADE
icbc_fc_dt: 0
get_icbc: True
do_geogrid: False
do_ungrib: True
do_metgrid: True
do_real: True
do_wrf: True
do_upp: False
upp_yaml: /glade/work/jaredlee/workflow/templates/run_upp.yaml
upp_domains:
  - '1'
